In [44]:
import numpy as np
import pandas as pd
import faiss                   # make faiss available
from sklearn.feature_extraction.text import TfidfVectorizer
import scipy.sparse as sp
import collections
import math
import copy
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

import itertools
import more_itertools as mit
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import string
import re
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /Users/MacBook/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

## Topic 4: Efficient Vector Space Retrieval

In [45]:
corpus = pd.read_csv('nfcorpus/dev.docs', sep='\t', names=['ID', 'TEXT'])
corpus.head()

        ID                                               TEXT
0  MED-118  alkylphenols human milk relations dietary habi...
1  MED-329  phosphate vascular toxin pubmed ncbi abstract ...
2  MED-330  dietary phosphorus acutely impairs endothelial...
3  MED-332  public health impact dietary phosphorus excess...
4  MED-334  differences total vitro digestible phosphorus ...

In [46]:
# function for corpus preprocessing: stemming

def preprocess_corpus(data):

    ps = PorterStemmer()

    def stemSentence(sentence,ps):
        token_words = word_tokenize(sentence)
        stem_sentence = []
        for word in token_words:
            stem_sentence.append(ps.stem(word))
            stem_sentence.append(" ")
        return "".join(stem_sentence)

    data['TEXT'] = data.apply(lambda x: stemSentence(x['TEXT'],ps), axis=1)

    return data

In [47]:
corpus = preprocess_corpus(corpus)
corpus.head()

        ID                                               TEXT
0  MED-118  alkylphenol human milk relat dietari habit cen...
1  MED-329  phosphat vascular toxin pubm ncbi abstract ele...
2  MED-330  dietari phosphoru acut impair endotheli functi...
3  MED-332  public health impact dietari phosphoru excess ...
4  MED-334  differ total vitro digest phosphoru content pl...

In [48]:
# apply term frequencies for each a single string (document)
def tf(qstring):
    
    
    # create token list out of document
    def tokenize(qstring):
        return qstring.split()

    # create bag of words from the string
    bow = tokenize(qstring)
    
    tf_dict = {}
    for word in bow:
        if word in tf_dict:
            tf_dict[word] += 1
        else:
            tf_dict[word] = 1
            
    for word in tf_dict:
        tf_dict[word] = 1 + math.log(tf_dict[word])
    
    return tf_dict

In [49]:
# We then call our function on every doc and store all these tf dictionaries. 
tf_dict = {}
for index, row in corpus.iterrows():
    doc_dict = tf(row['TEXT'])
    tf_dict[index] = doc_dict

# test if tfDict was created correctly
tf_dict[0]["alkylphenol"]
# alkylphenols for doc 0 : 1

1.0

In [50]:
# total number of documents in corpus
no_of_docs = len(corpus.index)
print(no_of_docs)

3193

In [51]:
# term - key, number of docs term occured in
def count_occurances():
    count_dict = {}
    for key in tf_dict:
        for key in tf_dict[key]:
            if key in count_dict:
                count_dict[key] += 1
            else:
                count_dict[key] = 1
    return count_dict

# test if count_occurances works
count_oc = count_occurances()
count_oc["alkylphenol"] 

# number of alkylphenols occurence in entire corpus = 7

7

In [52]:
# having total number of documents and number of occurances of each word in entire corpus we can calculate 
# idf for each term as log(total # of documents / # of documents with term in it)

# idf is calculated per each term, thus we create dictionary with term as a key and idf as a value
def idf():
    
    idf_dict = {}
    for key in count_oc:
        idf_dict[key] = math.log(no_of_docs/count_oc[key])
    return idf_dict

idf = idf()

# test if idf function works
idf["alkylphenol"]

# alkylphenols idf = 6.122806043659469

6.122806043659469

In [53]:
# cosntructing the final tf-idf dictionary; tf-idf is calculated as tf-idf(t, d) = tf(t, d) * idf(t)
# so for each key in tf dict we have to miltiply it with corresponsinf idf value

def tf_idf():
    d = copy.deepcopy(tf_dict)
    for doc, value in d.items():
        for word, value in d[doc].items():
            d[doc][word] = value * idf[word]
    return d

# test if tf_idf works
a = tf_idf()
print('Result from def:')
print(a[0]["alkylphenol"])

# excpected result for (term, doc) --> (alkylphenols, 0) =  0.008547008547008548 * 6.122806043659469 = 0.05
print('Manual result:')
idf["alkylphenol"] * tf_dict[0]["alkylphenol"]

# it works :)

Result from def:
6.122806043659469
Manual result:

6.122806043659469

In [54]:
# First we have to build TF-IDF matrix based on obtain dictionary. 
# Rows will correspond to docs in the corpus, while columns will represent unique words

#              word1       ...          wordn
#  doc1   tf_idf_value   ...      tf_idf_value
#  ...    tf_idf_value   ...      tf_idf_value
#  docn   tf_idf_value   ...      tf_idf_value
#

tf_idf_matrix = pd.DataFrame.from_dict(a, orient = 'index').fillna(0) # if word does not appear in doc we change NaN to
tf_idf_matrix = tf_idf_matrix.sort_index()
tf_idf_matrix = tf_idf_matrix.astype('float32')
tf_idf_matrix.head()

,alkylphenol,human,milk,relat,dietari,habit,central,taiwan,pubm,ncbi,...,six-year,inchianti,tuscani,studies-depress,eurosav,self-inflict,eurostat,suicide-record,scarciti,trim-and-fil
0,6.122806,2.886416,6.547579,2.90854,2.095849,5.898499,3.473596,5.503767,0.266507,0.27307,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.266507,0.27307,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.000000,0.000000,0.00000,2.597750,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.000000,0.00000,2.597750,0.000000,0.000000,0.000000,0.266507,0.27307,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.266507,0.27307,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
# Now we have to compare docs by computing cosine similarity between each vector (row) in dataframe
# For that we need to obtain 1. vector magintude 2. dot product between two vectors

def vector_magnitude(v):
    return np.linalg.norm(v)

def dot_product(v1, v2):
    return np.dot(v1,v2)

# Creating cosine similarity table (should be 3193 x 3193)
def cosine_similarity(v1, v2):
    return dot_product(v1, v2)/ (vector_magnitude(v1) * vector_magnitude(v2))
print(tf_idf_matrix.iloc[0])
cosine_similarity(tf_idf_matrix.iloc[0],tf_idf_matrix.iloc[0])

alkylphenol       6.122806
human             2.886416
milk              6.547579
relat             2.908540
dietari           2.095849
                    ...
self-inflict      0.000000
eurostat          0.000000
suicide-record    0.000000
scarciti          0.000000
trim-and-fil      0.000000
Name: 0, Length: 19930, dtype: float32

1.0000001

## Preclustering suggested in the lecture

In [56]:
sqrt_n = round(math.sqrt(no_of_docs))

def allocate_docs_to_clusters(rs, cosine = False, Faiss = False):
    
    def set_leaders(random_state = rs):
        #Set number of clusters at initialisation time
        sqrt_n = round(math.sqrt(no_of_docs))
        #we randomly select sqrt(N) documents from the corpus, which we call leaders
        leaders = tf_idf_matrix.sample(sqrt_n, random_state = rs)
        leaders = leaders.sort_index()
        return leaders

    leaders = set_leaders(random_state = rs)
    
    # For every other document in the collection
    # 1. Compute the similarities (cosine of the angle between TF-IDF vectors) with all leaders
    # 2. Add the document to the cluster of the most similar leader
    if (cosine and Faiss) or ((not cosine) and (not Faiss)):
        print('both true')
        return [], []
    
    
    elif cosine == True:
        cluster_list = []

        for i in range(sqrt_n):
            cluster_list.append([])

        for i in range(no_of_docs):
            cosines = []
            for j in leaders.index:
                cosines.append(cosine_similarity(tf_idf_matrix.loc[i],leaders.loc[j]))
            m = max(cosines)
            index_of_max = [l for l, b in enumerate(cosines) if b == m]
            cluster_list[index_of_max[0]].append(i) #if there are two equal max values of cosine similarity use the smaller index by default
        return leaders, cluster_list
    
    elif Faiss == True:
        
        leaders = leaders.astype('float32')
        index = faiss.IndexFlatL2(len(leaders.columns))
        index.add(np.ascontiguousarray(leaders.values))
        
        cluster_list = []

        for i in range(sqrt_n):
            cluster_list.append([])

        for i in range(no_of_docs):
            doc = np.array([tf_idf_matrix.loc[i]])
            D, I = index.search(doc, 1)
            cluster_list[I[0][0]].append(i)
        
        return leaders, cluster_list
    
    else:
        print('exeption')
        return [],[]

In [57]:
#construct function, which uses query q(should be already in the vector form) as input, required similarity of the doc to be retrieved - threshold, and
#necessary number of documents to be retrieved - K (5 most similar docs in the cluster by default)

def ir_preclustering(q, threshold = 0, K = 5): 
    
    sim_to_leaders = [] #array of cosine similarities of q to leaders
    retrieved_docs = [] #array of the most similar docs to be returned by the function
    
    for i in range(len(leaders.index)):
        sim_to_leaders.append(cosine_similarity(q,leaders.iloc[i]))
        m = max(sim_to_leaders)
        index_of_max = [l for l, b in enumerate(sim_to_leaders) if b == m] #odinal number of most similar leader => use this cluster
    
    sim_to_docs = [] #array of cosine similarities of q to all docs in the chosen cluster
    for doc in cluster_list[index_of_max[0]]:
        sim_to_docs.append(cosine_similarity(q,tf_idf_matrix.iloc[doc]))
        
    ins = np.argsort(sim_to_docs) #returns the indices that would sort an array of similarities to docs in ascending order
    ins = ins[::-1] #but we need descending (most similar in the beginning of the list)
    
    if threshold == 0: #proceed only with K
        if len(ins)>=K:
            for k in range(K):
                retrieved_docs.append(cluster_list[index_of_max[0]][ins[k]])
        else:
            K=len(ins)
            for k in range(K):
                retrieved_docs.append(cluster_list[index_of_max[0]][ins[k]])

        
    else:
        if sim_to_docs[ins[0]] < threshold:
            print('no documents satisfy necessary level of threshold similarity')
            return None
        
        for sim in sim_to_docs:
            if sim >= threshold:
                retrieved_docs.append(cluster_list[index_of_max[0]][sim_to_docs.index(sim)])
            if len(retrieved_docs) < K:
                print('number of documents that satisfy threshold similarity is less than required \(less than K\)')
    
    return corpus.iloc[retrieved_docs]

# repeat this procedure using FAISS instead of cosine similarity

In [58]:
#FAISS works only with type float32
tf_idf_matrix = tf_idf_matrix.astype('float32')

In [59]:
def set_indeces_for_faiss():
    index = faiss.IndexFlatL2(len(leaders.columns))
    index.add(np.ascontiguousarray(leaders.values))
    
    indices = []
    for i in range(len(leaders)):
        index2 = faiss.IndexFlatL2(len(leaders.columns))
        index2.add(np.ascontiguousarray(tf_idf_matrix.loc[cluster_list[i]]))
        indices.append(index2)
        
    return index, indices

In [60]:

#find the nearest leader
def ir_preclustering_faiss(q, K = 5, threshold = 0):
    
    

    q = np.array([q])
    D, I = index.search(q, 1) #returning distance and index of the nearest leader
    
    index2 = indices[I[0][0]]
    
    if threshold == 0: #proceed only with K
        
        if len(cluster_list[I[0][0]]) < K:
            print('asked number of documents to be retrieved is larger than the number of documents in the cluster; \nall documents in the cluster are retrieved')
            return corpus.iloc[cluster_list[I[0][0]]]   
        else:
            DD, II = index2.search(q, K) #returning distances and indexes of the nearest documents in the cluster (sorted by distance)
            return corpus.iloc[II[0]]
            
        
    else:
        DD, II = index2.search(q, K)
        DD = [1 - x for x in DD] #now DD are not distances, but similarities
        
        if DD[0] < threshold:
            return None
        
        for sim in DD:
            if sim < threshold:
                DD.pop(sim)
        
        if len(DD) < K:
                print('number of documents that satisfy threshold similarity is less than required \(less than K\)')
       
        return corpus.iloc[II[0]]

## K-means clustering

In [117]:
#Run the clustering algorithm
estimator = KMeans(n_clusters = sqrt_n, random_state = 1100)
model = estimator.fit(tf_idf_matrix)
model

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=57, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=1100, tol=0.0001, verbose=0)

In [118]:
#Generate cluster predictions and store in y_hat
y_hat = estimator.predict(tf_idf_matrix) #predicting to which cluster the query belongs
y_hat #array of belongings of docs to cluster

array([45, 45, 56, ...,  3,  3, 45], dtype=int32)

In [119]:
cluster_list_kmeans = []
for i in range(sqrt_n):
    cluster_list_kmeans.append([])

for i in range(no_of_docs):
    for j in range(sqrt_n):
        if y_hat[i] == j:
            cluster_list_kmeans[j].append(i)

In [120]:
#Since we have 57 clusters, we are going to compare the query vector with 57 vectors of cluster centroids
#All of cluster centroids are stored in the attribute cluster_centers
centers = np.array(model.cluster_centers_)

In [121]:
#construct function, which uses query q(should be already in the vector form) as input, required similarity of the doc to be retrieved - threshold, and
#necessary number of documents to be retrieved - K (5 most similar docs in the cluster by default)

def ir_preclustering_kmeans(q, threshold = 0, K = 5):
#     q = [q]
    sim_to_centers = [] #array of cosine similarities of q to centers
    retrieved_docs = [] #array of the most similar docs to be returned by the function
    
    for i in range(len(centers)):
        sim_to_centers.append(cosine_similarity(q,centers[i]))
    m = max(sim_to_centers)
    index_of_max = [l for l, b in enumerate(sim_to_centers) if b == m] #odinal number of most similar leader => use this cluster
    
    sim_to_docs = [] #array of cosine similarities of q to all docs in the chosen cluster
    for doc in cluster_list_kmeans[index_of_max[0]]:
        sim_to_docs.append(cosine_similarity(q,tf_idf_matrix.iloc[doc]))
        
    ins = np.argsort(sim_to_docs) #returns the indices that would sort an array of similarities to docs in ascending order
    ins = ins[::-1] #but we need descending (most similar in the beginning of the list)
    
    if threshold == 0: #proceed only with K
        if len(ins)>=K:
            for k in range(K):
                retrieved_docs.append(cluster_list_kmeans[index_of_max[0]][ins[k]])
        else:
            K=len(ins)
            for k in range(K):
                retrieved_docs.append(cluster_list_kmeans[index_of_max[0]][ins[k]])

        
    else:
        if sim_to_docs[ins[0]] < threshold:
            print('no documents satisfy necessary level of threshold similarity')
            return None
        
        for sim in sim_to_docs:
            if sim >= threshold:
                retrieved_docs.append(cluster_list_kmeans[index_of_max[0]][sim_to_docs.index(sim)])
            if len(retrieved_docs) < K:
                print('number of documents that satisfy threshold similarity is less than required \(less than K\)')
    
    return corpus.iloc[retrieved_docs]

## Vectorize query

In [66]:
queries_relevance = pd.read_csv('nfcorpus/dev.2-1-0.qrel', sep='\t', names=['QUERY_ID', '0', 'DOC_ID', 'RELEVANCE_LEVEL'])
queries_relevance.head(10)

  QUERY_ID  0    DOC_ID  RELEVANCE_LEVEL
0  PLAIN-1  0  MED-2421                2
1  PLAIN-1  0  MED-2422                2
2  PLAIN-1  0  MED-2416                2
3  PLAIN-1  0  MED-2423                2
4  PLAIN-1  0  MED-2417                2
5  PLAIN-1  0  MED-2418                2
6  PLAIN-1  0  MED-4451                2
7  PLAIN-1  0  MED-2420                2
8  PLAIN-1  0  MED-2414                1
9  PLAIN-1  0  MED-4070                1

In [67]:
queries_text = pd.read_csv('nfcorpus/dev.all.queries', sep='\t', names=['ID', 'TEXT'])
queries_text.head(10)

           ID                                               TEXT
0     PLAIN-1  why deep fried foods may cause cancer in the l...
1  PLAIN-1007  ddt - - persistent organic pollutants , indust...
2   PLAIN-101  how to treat multiple sclerosis with diet mult...
3  PLAIN-1017  detoxification - - cancer , raw food , heart h...
4  PLAIN-1027  dietary guidelines - - heart disease , cardiov...
5  PLAIN-1038  dogs - - meat , animal products , cats , heart...
6  PLAIN-1049  dr. david spence - - heart health , heart dise...
7  PLAIN-1065  dr. walter kempner - - mortality , heart disea...
8  PLAIN-1077  dulse - - thyroid health , hijiki , sushi , io...
9  PLAIN-1087  easter island - - mortality , muscle strength ...

In [68]:
## preprocessing of the text of the queries

def preprocess_queries(corpus, queries):

    def remove_punctuations(text): # remove punctuation
        for punctuation in string.punctuation:
            text = text.replace(punctuation, '')
        return text

    def remove_numbers(text): # remove numbers
        return re.sub('[0-9]+', '', text)

    def lower_case(text): # lower case
        text = text.lower()
        return text

    def tokenize(text): #tokenize
        return word_tokenize(text)

    stop = set(stopwords.words('english'))
    def stop_words(tokens): # stop words
        filtered_words = []
        for word in tokens:
            if word not in stop:
                filtered_words.append(word)
        return filtered_words

    ps = PorterStemmer()
    def stemming(tokens, ps): # stemming
        return [ps.stem(w) for w in tokens]

    def corpus_vocab(corpus):
        vocab = []
        corpus_tokens = corpus.apply(lambda x: word_tokenize(x['TEXT']), axis=1)
        for i, j in corpus_tokens.iteritems():
            for token in j:
                if token not in vocab:
                    vocab.append(token)
        return vocab

    v = corpus_vocab(corpus)
    def filter_query(tokens):
        t = []
        for token in tokens:
            if token in v:
                t.append(token)
        return t

    # apply functions
    queries['TEXT'] = queries.apply(lambda x: remove_punctuations(x['TEXT']), axis=1)
    queries['TEXT'] = queries.apply(lambda x: remove_numbers(x['TEXT']), axis=1)
    queries['TEXT'] = queries.apply(lambda x: lower_case(x['TEXT']), axis=1)
    queries['TEXT'] = queries.apply(lambda x: tokenize(x['TEXT']), axis=1)
    queries['TEXT'] = queries.apply(lambda x: stop_words(x['TEXT']), axis=1)
    queries['TEXT'] = queries.apply(lambda x: stemming(x['TEXT'],ps), axis=1)
    queries['TEXT'] = queries.apply(lambda x: filter_query(x['TEXT']), axis=1)

    return queries

In [69]:
queries_text = preprocess_queries(corpus, queries_text)
queries_text.head()

           ID                                               TEXT
0     PLAIN-1  [deep, fri, food, may, caus, cancer, latest, s...
1  PLAIN-1007  [ddt, persist, organ, pollut, industri, toxin,...
2   PLAIN-101  [treat, multipl, sclerosi, diet, multipl, scle...
3  PLAIN-1017  [detoxif, cancer, raw, food, heart, health, he...
4  PLAIN-1027  [dietari, guidelin, heart, diseas, cardiovascu...

In [70]:
tf_idf_queries = tf_idf_matrix[0:0]
tf_idf_queries.head()

Empty DataFrame
Columns: [alkylphenol, human, milk, relat, dietari, habit, central, taiwan, pubm, ncbi, abstract, aim, studi, determin, concentr, num, nonylphenol, np, octylphenol, op, sampl, examin, factor, includ, mother, demograph, women, consum, median, amount, cook, oil, significantli, higher, ng/g, consumpt, beta, fish, capsul, adjust, age, bodi, mass, index, bmi, process, product, food, pattern, meat, analysi, strongli, aid, suggest, nurs, order, protect, infant, np/op, exposur, elsevi, right, reserv, phosphat, vascular, toxin, elev, level, advanc, renal, failur, dysregul, calcium, parathyroid, hormon, vitamin, contribut, complex, chronic, kidney, disease-miner, bone, diseas, ckd-mbd, converg, evid, vitro, clinic, epidemiolog, increas, calcif, mortal, vessel, expos, high, condit, develop, apoptosi, convert, bone-lik, ...]
Index: []

[0 rows x 19930 columns]

In [71]:
for i in range(len(queries_text)):
    tf_idf_queries = tf_idf_queries.append(pd.Series(0, index=tf_idf_queries.columns), ignore_index=True)
    for token in queries_text['TEXT'][i]:
        for col in tf_idf_queries.columns:
            if token == col:
                tf_idf_queries[col][i] = tf_idf_queries[col][i] + 1

In [72]:
tf_idf_queries = tf_idf_queries.astype('float32')

In [73]:
def vectorize_query(textstring):
    if type(textstring) == str:
        tokenized_query = textstring.split()
    else:
        tokenized_query = textstring
        
    df_query = tf_idf_matrix[0:0] #dataframe of tf-idf weights of a query
    df_query = df_query.append(pd.Series(0, index=df_query.columns), ignore_index=True)
    for token in tokenized_query:
        for col in df_query.columns:
            if token == col:
                df_query[col][0] = df_query[col][0] + 1 #raw term frequency
    
    df_query = df_query.replace(0, np.nan)
    
    df_query = np.log(df_query) + 1 #log term freq(as in the slides)
    
    df_query = df_query.fillna(0)
    
    for col in df_query.columns:
        df_query[col][0] = df_query[col][0] * idf[col]
        
    return df_query

## Information retrieval

In [74]:
def retrieve_with_preclustering(string_query, k = 5, IDs_of_retrieved_docs = False):
    vector_q = vectorize_query(string_query)
    return ir_preclustering(vector_q.iloc[0], K = k)

## Find all relevant documents for the query

In [75]:
def true_relevant_docs(string_query):
    query_row = (queries_text.loc[queries_text['TEXT'].isin([string_query])])
    query_id = query_row.iloc[0]["ID"]
    relevance_lvl = [1, 2]
    return queries_relevance.loc[queries_relevance['QUERY_ID'].isin([query_id]) & queries_relevance['RELEVANCE_LEVEL'].isin(relevance_lvl)]

## Evaluate performance by:
 Precision
 MAP 
 nDCG

In [76]:
def apk(actual, predicted):
    """
    Computes the average precision at k.
    This function computes the average prescision at k between two lists of
    items.
    Parameters
    ----------
    actual : list
             A list of elements that are to be predicted (order doesn't matter)
    predicted : list
                A list of predicted elements (order does matter)
    k : int, optional
        The maximum number of predicted elements
    Returns
    -------
    score : double
            The average precision at k over the input lists
    """

    score = 0.0
    num_hits = 0.0

    for i,p in enumerate(predicted):
        if p in actual and p not in predicted[:i]:
            num_hits += 1.0
            score += num_hits / (i+1.0)

    if not actual:
        return 0.0

    return score / min(len(actual), len(predicted))

def mapk(actual, predicted, k=5):
    """
    Computes the mean average precision at k.
    This function computes the mean average prescision at k between two lists
    of lists of items.
    Parameters
    ----------
    actual : list
             A list of lists of elements that are to be predicted 
             (order doesn't matter in the lists)
    predicted : list
                A list of lists of predicted elements
                (order matters in the lists)
    k : int, optional
        The maximum number of predicted elements
    Returns
    -------
    score : double
            The mean average precision at k over the input lists
    """
    return np.mean([apk(a,p,k) for a,p in zip(actual, predicted)])

In [77]:
def dcg(element_list):
    """
    Discounted Cumulative Gain (DCG)
    Parameters:
        element_list - a list of ranks Ex: [5,4,2,2,1]
    Returns:
        score
    """
    score = 0.0
    for order, rank in enumerate(element_list):
        score += float(rank)/math.log((order+2))
    return score


def ndcg(reference, hypothesis):
    """
    Normalized Discounted Cumulative Gain (nDCG)
    Normalized version of DCG:
        nDCG = DCG(hypothesis)/DCG(reference)
    Parameters:
        reference   - a gold standard (perfect) ordering Ex: [5,4,3,2,1]
        hypothesis  - a proposed ordering Ex: [5,2,2,3,1]
    Returns:
        ndcg_score  - normalized score
    """
    if dcg(reference) == 0:
        return 0 
    else:
        return dcg(hypothesis)/dcg(reference)

In [78]:
def evaluate_retrieve_with_preclustering(position):
    
    ## takes ordinal number of a query as an input 
    ## returns the triple (Precision, Average Precision, Normalized Discounted Cumulative Gain)
    
    retrieved_df = ir_preclustering(tf_idf_queries.iloc[position])
    ids_retrieved = []
    for i in range(len(retrieved_df)):
        ids_retrieved.append(retrieved_df.iloc[i].ID)
    ids_retrieved.sort()
    
    relevant = true_relevant_docs(queries_text['TEXT'][position])
    ids_true_relevant = []
    for i in range(len(relevant)):
        ids_true_relevant.append(relevant.iloc[i].DOC_ID)
    ids_true_relevant.sort()
    
    #count true positives and false positives
    tp = 0
    fp = 0
    for i in ids_retrieved:
        for j in ids_true_relevant:
            if i == j:
                tp += 1 
                break
            else:
                if i < j:
                    fp += 1 
                    break
                else:
                    continue
    if (tp == 0) & (fp == 0):
        precision = 0
    else:
        precision = tp/(tp+fp)
    #cannot calculate recall, since we predefined the number of retrieved documents => apriori algorithm cannot retrieve all documents
    
    #then calculate Average precision across retrieved documents
    ap = apk(ids_true_relevant, ids_retrieved)
    
    #since we have graded relevance annotations, we can also calculate Normalized Discounted Cumulative Gain
    list_of_ranks_of_retrieved_docs = []
    for i in ids_retrieved:
        if i in ids_true_relevant:
            list_of_ranks_of_retrieved_docs.append(relevant.loc[relevant['DOC_ID'].isin([i])].RELEVANCE_LEVEL.iloc[0])
        else:
            list_of_ranks_of_retrieved_docs.append(0)

                                               
    list_of_ranks_of_relevant_docs = []
    for i in ids_true_relevant:
        list_of_ranks_of_relevant_docs.append(relevant.loc[relevant['DOC_ID'].isin([i])].RELEVANCE_LEVEL.iloc[0])
    list_of_ranks_of_relevant_docs.sort(reverse = True)
    
    k=len(list_of_ranks_of_retrieved_docs)
    list_of_ranks_of_relevant_docs = list_of_ranks_of_relevant_docs[:k]
        
    return precision, ap, ndcg(list_of_ranks_of_relevant_docs, list_of_ranks_of_retrieved_docs)

In [79]:
def evaluate_preclustering():
    evaluation = queries_text.copy()
    evaluation.insert(2, "Precision", 0)
    evaluation.insert(3, "Average Precision", 0)
    evaluation.insert(4, "nDCG", 0)
    
    for i in range(len(evaluation)):

        p, a, n = evaluate_retrieve_with_preclustering(i,)
        evaluation.loc[i, 'Precision'] = p
        evaluation.loc[i, 'Average Precision'] = a
        evaluation.loc[i, 'nDCG'] = n
    
    print('Average precision across all queries = ' + str(evaluation['Precision'].mean()))
    print('Mean Average Precision = ' + str(evaluation['Average Precision'].mean()))
    print('Average nDCG = ' + str(evaluation['nDCG'].mean()))
    
    return evaluation

In [80]:
leaders, cluster_list = allocate_docs_to_clusters(11, cosine = True, Faiss = False)
evaluate_with_leaders_state_11 = evaluate_preclustering()

Average precision across all queries = 0.16420512820512825
Mean Average Precision = 0.10971282051282048
Average nDCG = 0.13930220616406092

In [81]:
evaluate_with_leaders_state_11.head(10)

,ID,TEXT,Precision,Average Precision,nDCG
0,PLAIN-1,"[deep, fri, food, may, caus, cancer, latest, s...",0.2,0.040000,0.065603
1,PLAIN-1007,"[ddt, persist, organ, pollut, industri, toxin,...",0.4,0.280000,0.470365
2,PLAIN-101,"[treat, multipl, sclerosi, diet, multipl, scle...",0.0,0.000000,0.000000
3,PLAIN-1017,"[detoxif, cancer, raw, food, heart, health, he...",0.0,0.000000,0.000000
4,PLAIN-1027,"[dietari, guidelin, heart, diseas, cardiovascu...",0.0,0.000000,0.000000
5,PLAIN-1038,"[dog, meat, anim, product, cat, heart, health,...",0.0,0.000000,0.000000
6,PLAIN-1049,"[dr, heart, health, heart, diseas, egg, choles...",0.2,0.066667,0.181542
7,PLAIN-1065,"[dr, walter, mortal, heart, diseas, heart, hea...",0.0,0.000000,0.000000
8,PLAIN-1077,"[thyroid, health, hijiki, sushi, iodin, sea, v...",0.6,0.600000,0.722727
9,PLAIN-1087,"[easter, island, mortal, muscl, strength, morb...",0.0,0.000000,0.000000

In [82]:
evaluate_with_leaders_state_11.describe()

        Precision  Average Precision        nDCG
count  325.000000         325.000000  325.000000
mean     0.164205           0.109713    0.139302
std      0.271767           0.228497    0.245861
min      0.000000           0.000000    0.000000
25%      0.000000           0.000000    0.000000
50%      0.000000           0.000000    0.000000
75%      0.200000           0.066667    0.168954
max      1.000000           1.000000    1.000000

In [83]:
leaders, cluster_list = allocate_docs_to_clusters(110, cosine = True, Faiss = False)
evaluate_with_leaders_state_110 = evaluate_preclustering()

Average precision across all queries = 0.17625641025641028
Mean Average Precision = 0.10968717948717945
Average nDCG = 0.1452283702370656

In [84]:
evaluate_with_leaders_state_110.head(10)

,ID,TEXT,Precision,Average Precision,nDCG
0,PLAIN-1,"[deep, fri, food, may, caus, cancer, latest, s...",0.6,0.453333,0.489553
1,PLAIN-1007,"[ddt, persist, organ, pollut, industri, toxin,...",0.8,0.543333,0.660840
2,PLAIN-101,"[treat, multipl, sclerosi, diet, multipl, scle...",0.0,0.000000,0.000000
3,PLAIN-1017,"[detoxif, cancer, raw, food, heart, health, he...",0.0,0.000000,0.000000
4,PLAIN-1027,"[dietari, guidelin, heart, diseas, cardiovascu...",0.8,0.543333,0.660840
5,PLAIN-1038,"[dog, meat, anim, product, cat, heart, health,...",0.0,0.000000,0.000000
6,PLAIN-1049,"[dr, heart, health, heart, diseas, egg, choles...",0.0,0.000000,0.000000
7,PLAIN-1065,"[dr, walter, mortal, heart, diseas, heart, hea...",0.0,0.000000,0.000000
8,PLAIN-1077,"[thyroid, health, hijiki, sushi, iodin, sea, v...",0.0,0.000000,0.000000
9,PLAIN-1087,"[easter, island, mortal, muscl, strength, morb...",0.2,0.050000,0.146068

In [85]:
evaluate_with_leaders_state_110.describe()

        Precision  Average Precision        nDCG
count  325.000000         325.000000  325.000000
mean     0.176256           0.109687    0.145228
std      0.271287           0.219125    0.237368
min      0.000000           0.000000    0.000000
25%      0.000000           0.000000    0.000000
50%      0.000000           0.000000    0.000000
75%      0.250000           0.100000    0.211671
max      1.000000           1.000000    1.000000

In [86]:
leaders, cluster_list = allocate_docs_to_clusters(1100, cosine = True, Faiss = False)

In [87]:
%%time
evaluate_with_leaders_state_1100 = evaluate_preclustering()

Average precision across all queries = 0.22158974358974376
Mean Average Precision = 0.1494820512820514
Average nDCG = 0.187614632924556
CPU times: user 1min 47s, sys: 1.17 s, total: 1min 48s
Wall time: 56.5 s

In [88]:
evaluate_with_leaders_state_1100.head(10)

,ID,TEXT,Precision,Average Precision,nDCG
0,PLAIN-1,"[deep, fri, food, may, caus, cancer, latest, s...",0.8,0.543333,0.415210
1,PLAIN-1007,"[ddt, persist, organ, pollut, industri, toxin,...",0.0,0.000000,0.000000
2,PLAIN-101,"[treat, multipl, sclerosi, diet, multipl, scle...",0.0,0.000000,0.000000
3,PLAIN-1017,"[detoxif, cancer, raw, food, heart, health, he...",0.2,0.040000,0.131205
4,PLAIN-1027,"[dietari, guidelin, heart, diseas, cardiovascu...",0.2,0.040000,0.131205
5,PLAIN-1038,"[dog, meat, anim, product, cat, heart, health,...",0.0,0.000000,0.000000
6,PLAIN-1049,"[dr, heart, health, heart, diseas, egg, choles...",0.0,0.000000,0.000000
7,PLAIN-1065,"[dr, walter, mortal, heart, diseas, heart, hea...",0.0,0.000000,0.000000
8,PLAIN-1077,"[thyroid, health, hijiki, sushi, iodin, sea, v...",0.6,0.600000,0.722727
9,PLAIN-1087,"[easter, island, mortal, muscl, strength, morb...",0.2,0.066667,0.169580

In [89]:
evaluate_with_leaders_state_1100.describe()

        Precision  Average Precision        nDCG
count  325.000000         325.000000  325.000000
mean     0.221590           0.149482    0.187615
std      0.316222           0.270481    0.280451
min      0.000000           0.000000    0.000000
25%      0.000000           0.000000    0.000000
50%      0.000000           0.000000    0.000000
75%      0.400000           0.166667    0.315648
max      1.000000           1.000000    1.000000

## Evaluate FAISS

In [90]:
def retrieve_with_preclustering_faiss(string_query, k = 5, IDs_of_retrieved_docs = False):
    vector_q = vectorize_query(string_query)
    return ir_preclustering_faiss(vector_q.iloc[0].astype('float32'), K = k)

In [91]:
def evaluate_retrieve_with_preclustering_faiss(position):
    ## returns the triple (Precision, Average Precision, Normalized Discounted Cumulative Gain)
    
    retrieved_df = ir_preclustering_faiss(tf_idf_queries.iloc[position].astype('float32'))
    ids_retrieved = []
    
    for i in range(len(retrieved_df)):
        ids_retrieved.append(retrieved_df.iloc[i]['ID'])
    ids_retrieved.sort()
    
    relevant = true_relevant_docs(queries_text['TEXT'][position])
    ids_true_relevant = []
    for i in range(len(relevant)):
        ids_true_relevant.append(relevant.iloc[i].DOC_ID)
    ids_true_relevant.sort()
    
    #count true positives and false positives
    tp = 0
    fp = 0
    for i in ids_retrieved:
        for j in ids_true_relevant:
            if i == j:
                tp += 1 
                break
            else:
                if i < j:
                    fp += 1 
                    break
                else:
                    continue
    if (tp == 0) & (fp == 0):
        precision = 0
    else:
        precision = tp/(tp+fp)
    #cannot calculate recall, since we predefined the number of retrieved documents => apriori algorithm cannot retrieve all documents
    
    #then calculate Average precision across retrieved documents
    ap = apk(ids_true_relevant, ids_retrieved)
    
    #since we have graded relevance annotations, we can also calculate Normalized Discounted Cumulative Gain
    list_of_ranks_of_retrieved_docs = []
    for i in ids_retrieved:
        if i in ids_true_relevant:
            list_of_ranks_of_retrieved_docs.append(relevant.loc[relevant['DOC_ID'].isin([i])].RELEVANCE_LEVEL.iloc[0])
        else:
            list_of_ranks_of_retrieved_docs.append(0)

                                               
    list_of_ranks_of_relevant_docs = []
    for i in ids_true_relevant:
        list_of_ranks_of_relevant_docs.append(relevant.loc[relevant['DOC_ID'].isin([i])].RELEVANCE_LEVEL.iloc[0])
    list_of_ranks_of_relevant_docs.sort(reverse = True)
    
    k=len(list_of_ranks_of_retrieved_docs)
    list_of_ranks_of_relevant_docs = list_of_ranks_of_relevant_docs[:k]
        
    return precision, ap, ndcg(list_of_ranks_of_relevant_docs, list_of_ranks_of_retrieved_docs)

In [92]:
def evaluate_preclustering_faiss():
    evaluation = queries_text.copy()
    evaluation.insert(2, "Precision", 0)
    evaluation.insert(3, "Average Precision", 0)
    evaluation.insert(4, "nDCG", 0)
    
    for i in range(len(evaluation)):

        p, a, n = evaluate_retrieve_with_preclustering_faiss(i)
        evaluation.loc[i, 'Precision'] = p
        evaluation.loc[i, 'Average Precision'] = a
        evaluation.loc[i, 'nDCG'] = n
    
    print('Average precision across all queries = ' + str(evaluation['Precision'].mean()))
    print('Mean Average Precision = ' + str(evaluation['Average Precision'].mean()))
    print('Average nDCG = ' + str(evaluation['nDCG'].mean()))
    
    return evaluation

In [93]:
leaders, cluster_list = allocate_docs_to_clusters(11, cosine = False, Faiss = True)
index, indices = set_indeces_for_faiss()
evaluate_with_leaders_state_11_faiss = evaluate_preclustering_faiss()

asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
Average precision across all queries = 0.014461538461538465
Mean Average Precision = 0.008935897435897436
Average nDCG = 0.012320890414390748

In [94]:
evaluate_with_leaders_state_11_faiss.head()

,ID,TEXT,Precision,Average Precision,nDCG
0,PLAIN-1,"[deep, fri, food, may, caus, cancer, latest, s...",0.0,0.0,0.0
1,PLAIN-1007,"[ddt, persist, organ, pollut, industri, toxin,...",0.0,0.0,0.0
2,PLAIN-101,"[treat, multipl, sclerosi, diet, multipl, scle...",0.0,0.0,0.0
3,PLAIN-1017,"[detoxif, cancer, raw, food, heart, health, he...",0.0,0.0,0.0
4,PLAIN-1027,"[dietari, guidelin, heart, diseas, cardiovascu...",0.0,0.0,0.0

In [95]:
evaluate_with_leaders_state_11_faiss.describe()

        Precision  Average Precision        nDCG
count  325.000000         325.000000  325.000000
mean     0.014462           0.008936    0.012321
std      0.080066           0.066544    0.075102
min      0.000000           0.000000    0.000000
25%      0.000000           0.000000    0.000000
50%      0.000000           0.000000    0.000000
75%      0.000000           0.000000    0.000000
max      1.000000           1.000000    1.000000

In [96]:
leaders, cluster_list = allocate_docs_to_clusters(110, cosine = False, Faiss = True)
index, indices = set_indeces_for_faiss()
evaluate_with_leaders_state_110_faiss = evaluate_preclustering_faiss()

asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
Average precision across all queries = 0.024615384615384615
Mean Average Precision = 0.019323076923076922
Average nDCG = 0.020270599734524705

In [97]:
evaluate_with_leaders_state_110_faiss.head(10)

,ID,TEXT,Precision,Average Precision,nDCG
0,PLAIN-1,"[deep, fri, food, may, caus, cancer, latest, s...",0.0,0.0,0.0
1,PLAIN-1007,"[ddt, persist, organ, pollut, industri, toxin,...",0.0,0.0,0.0
2,PLAIN-101,"[treat, multipl, sclerosi, diet, multipl, scle...",0.0,0.0,0.0
3,PLAIN-1017,"[detoxif, cancer, raw, food, heart, health, he...",0.0,0.0,0.0
4,PLAIN-1027,"[dietari, guidelin, heart, diseas, cardiovascu...",0.0,0.0,0.0
5,PLAIN-1038,"[dog, meat, anim, product, cat, heart, health,...",0.0,0.0,0.0
6,PLAIN-1049,"[dr, heart, health, heart, diseas, egg, choles...",0.0,0.0,0.0
7,PLAIN-1065,"[dr, walter, mortal, heart, diseas, heart, hea...",0.0,0.0,0.0
8,PLAIN-1077,"[thyroid, health, hijiki, sushi, iodin, sea, v...",0.0,0.0,0.0
9,PLAIN-1087,"[easter, island, mortal, muscl, strength, morb...",0.0,0.0,0.0

In [98]:
evaluate_with_leaders_state_110_faiss.describe()

        Precision  Average Precision        nDCG
count  325.000000         325.000000  325.000000
mean     0.024615           0.019323    0.020271
std      0.133318           0.119551    0.104334
min      0.000000           0.000000    0.000000
25%      0.000000           0.000000    0.000000
50%      0.000000           0.000000    0.000000
75%      0.000000           0.000000    0.000000
max      1.000000           1.000000    1.000000

In [99]:
leaders, cluster_list = allocate_docs_to_clusters(1100, cosine = False, Faiss = True)
index, indices = set_indeces_for_faiss()

In [100]:
%%time
evaluate_with_leaders_state_1100_faiss = evaluate_preclustering_faiss()

asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
asked number of documents to be retrieved is larger than the number of documents in the cluster;
all documents in the cluster are retrieved
Average precision across all queries = 0.014923076923076924
Mean Average Precision = 0.007574358974358975
Average nDCG = 0.012720872828219236
CPU times: user 1min 25s, sys: 2.47 s, total: 1min 27s
Wall time: 25.2 s

In [101]:
evaluate_with_leaders_state_1100_faiss.head(10)

,ID,TEXT,Precision,Average Precision,nDCG
0,PLAIN-1,"[deep, fri, food, may, caus, cancer, latest, s...",0.0,0.00,0.000000
1,PLAIN-1007,"[ddt, persist, organ, pollut, industri, toxin,...",0.2,0.05,0.146068
2,PLAIN-101,"[treat, multipl, sclerosi, diet, multipl, scle...",0.0,0.00,0.000000
3,PLAIN-1017,"[detoxif, cancer, raw, food, heart, health, he...",0.0,0.00,0.000000
4,PLAIN-1027,"[dietari, guidelin, heart, diseas, cardiovascu...",0.0,0.00,0.000000
5,PLAIN-1038,"[dog, meat, anim, product, cat, heart, health,...",0.0,0.00,0.000000
6,PLAIN-1049,"[dr, heart, health, heart, diseas, egg, choles...",0.0,0.00,0.000000
7,PLAIN-1065,"[dr, walter, mortal, heart, diseas, heart, hea...",0.0,0.00,0.000000
8,PLAIN-1077,"[thyroid, health, hijiki, sushi, iodin, sea, v...",0.0,0.00,0.000000
9,PLAIN-1087,"[easter, island, mortal, muscl, strength, morb...",0.0,0.00,0.000000

In [102]:
evaluate_with_leaders_state_1100_faiss.describe()

        Precision  Average Precision        nDCG
count  325.000000         325.000000  325.000000
mean     0.014923           0.007574    0.012721
std      0.081841           0.042644    0.066378
min      0.000000           0.000000    0.000000
25%      0.000000           0.000000    0.000000
50%      0.000000           0.000000    0.000000
75%      0.000000           0.000000    0.000000
max      1.000000           0.500000    0.630930

## Evaluate K-Means

In [103]:
def retrieve_with_preclustering_kmeans(string_query, k = 5, IDs_of_retrieved_docs = False):
    vector_q = vectorize_query(string_query)
    return ir_preclustering_kmeans(vector_q.iloc[0].astype('float32'), K = k)

In [104]:
def evaluate_retrieve_with_preclustering_kmeans(position):
    ## returns the triple (Precision, Average Precision, Normalized Discounted Cumulative Gain)
    
    retrieved_df = ir_preclustering_kmeans(tf_idf_queries.iloc[position].astype('float32'))
    ids_retrieved = []
    for i in range(len(retrieved_df)):
        ids_retrieved.append(retrieved_df.iloc[i].ID)
    ids_retrieved.sort()
    
    relevant = true_relevant_docs(queries_text['TEXT'][position])
    ids_true_relevant = []
    for i in range(len(relevant)):
        ids_true_relevant.append(relevant.iloc[i].DOC_ID)
    ids_true_relevant.sort()
    
    #count true positives and false positives
    tp = 0
    fp = 0
    for i in ids_retrieved:
        for j in ids_true_relevant:
            if i == j:
                tp += 1 
                break
            else:
                if i < j:
                    fp += 1 
                    break
                else:
                    continue
    if (tp == 0) & (fp == 0):
        precision = 0
    else:
        precision = tp/(tp+fp)
    #cannot calculate recall, since we predefined the number of retrieved documents => apriori algorithm cannot retrieve all documents
    
    #then calculate Average precision across retrieved documents
    ap = apk(ids_true_relevant, ids_retrieved)
    
    #since we have graded relevance annotations, we can also calculate Normalized Discounted Cumulative Gain
    list_of_ranks_of_retrieved_docs = []
    for i in ids_retrieved:
        if i in ids_true_relevant:
            list_of_ranks_of_retrieved_docs.append(relevant.loc[relevant['DOC_ID'].isin([i])].RELEVANCE_LEVEL.iloc[0])
        else:
            list_of_ranks_of_retrieved_docs.append(0)

                                               
    list_of_ranks_of_relevant_docs = []
    for i in ids_true_relevant:
        list_of_ranks_of_relevant_docs.append(relevant.loc[relevant['DOC_ID'].isin([i])].RELEVANCE_LEVEL.iloc[0])
    list_of_ranks_of_relevant_docs.sort(reverse = True)
    
    k=len(list_of_ranks_of_retrieved_docs)
    list_of_ranks_of_relevant_docs = list_of_ranks_of_relevant_docs[:k]
        
    return precision, ap, ndcg(list_of_ranks_of_relevant_docs, list_of_ranks_of_retrieved_docs)

In [105]:
def evaluate_preclustering_kmeans():
    evaluation = queries_text.copy()
    evaluation.insert(2, "Precision", 0)
    evaluation.insert(3, "Average Precision", 0)
    evaluation.insert(4, "nDCG", 0)
    
    for i in range(len(evaluation)):

        p, a, n = evaluate_retrieve_with_preclustering_kmeans(i)
        evaluation.loc[i, 'Precision'] = p
        evaluation.loc[i, 'Average Precision'] = a
        evaluation.loc[i, 'nDCG'] = n
    
    print('Average precision across all queries = ' + str(evaluation['Precision'].mean()))
    print('Mean Average Precision = ' + str(evaluation['Average Precision'].mean()))
    print('Average nDCG = ' + str(evaluation['nDCG'].mean()))
    
    return evaluation

In [106]:
evaluate_kmeans_random_state_11 = evaluate_preclustering_kmeans()

Average precision across all queries = 0.3107692307692311
Mean Average Precision = 0.2123717948717949
Average nDCG = 0.2688083624757651

In [107]:
evaluate_kmeans_random_state_11.head(10)

,ID,TEXT,Precision,Average Precision,nDCG
0,PLAIN-1,"[deep, fri, food, may, caus, cancer, latest, s...",0.80,0.800000,0.710971
1,PLAIN-1007,"[ddt, persist, organ, pollut, industri, toxin,...",0.40,0.166667,0.315648
2,PLAIN-101,"[treat, multipl, sclerosi, diet, multipl, scle...",0.20,0.066667,0.169580
3,PLAIN-1017,"[detoxif, cancer, raw, food, heart, health, he...",0.00,0.000000,0.000000
4,PLAIN-1027,"[dietari, guidelin, heart, diseas, cardiovascu...",0.20,0.050000,0.146068
5,PLAIN-1038,"[dog, meat, anim, product, cat, heart, health,...",0.25,0.050000,0.146068
6,PLAIN-1049,"[dr, heart, health, heart, diseas, egg, choles...",0.00,0.000000,0.000000
7,PLAIN-1065,"[dr, walter, mortal, heart, diseas, heart, hea...",0.00,0.000000,0.000000
8,PLAIN-1077,"[thyroid, health, hijiki, sushi, iodin, sea, v...",0.20,0.040000,0.131205
9,PLAIN-1087,"[easter, island, mortal, muscl, strength, morb...",0.20,0.066667,0.169580

In [108]:
evaluate_kmeans_random_state_11.describe()

        Precision  Average Precision        nDCG
count  325.000000         325.000000  325.000000
mean     0.310769           0.212372    0.268808
std      0.325897           0.295106    0.296879
min      0.000000           0.000000    0.000000
25%      0.000000           0.000000    0.000000
50%      0.200000           0.066667    0.169580
75%      0.500000           0.325000    0.446854
max      1.000000           1.000000    1.000000

In [114]:
evaluate_kmeans_random_state_110 = evaluate_preclustering_kmeans()

Average precision across all queries = 0.2790769230769232
Mean Average Precision = 0.17047692307692305
Average nDCG = 0.22723860041058136

In [115]:
evaluate_kmeans_random_state_110.head(10)

,ID,TEXT,Precision,Average Precision,nDCG
0,PLAIN-1,"[deep, fri, food, may, caus, cancer, latest, s...",0.4,0.400000,0.446153
1,PLAIN-1007,"[ddt, persist, organ, pollut, industri, toxin,...",0.4,0.146667,0.300785
2,PLAIN-101,"[treat, multipl, sclerosi, diet, multipl, scle...",0.4,0.146667,0.235183
3,PLAIN-1017,"[detoxif, cancer, raw, food, heart, health, he...",0.0,0.000000,0.000000
4,PLAIN-1027,"[dietari, guidelin, heart, diseas, cardiovascu...",0.2,0.050000,0.146068
5,PLAIN-1038,"[dog, meat, anim, product, cat, heart, health,...",0.2,0.040000,0.131205
6,PLAIN-1049,"[dr, heart, health, heart, diseas, egg, choles...",0.0,0.000000,0.000000
7,PLAIN-1065,"[dr, walter, mortal, heart, diseas, heart, hea...",0.0,0.000000,0.000000
8,PLAIN-1077,"[thyroid, health, hijiki, sushi, iodin, sea, v...",0.4,0.233333,0.383566
9,PLAIN-1087,"[easter, island, mortal, muscl, strength, morb...",0.0,0.000000,0.000000

In [116]:
evaluate_kmeans_random_state_110.describe()

        Precision  Average Precision        nDCG
count  325.000000         325.000000  325.000000
mean     0.279077           0.170477    0.227239
std      0.300930           0.255067    0.263080
min      0.000000           0.000000    0.000000
25%      0.000000           0.000000    0.000000
50%      0.200000           0.050000    0.146068
75%      0.400000           0.233333    0.383566
max      1.000000           1.000000    1.000000

In [122]:
%%time
evaluate_kmeans_random_state_1100 = evaluate_preclustering_kmeans()

Average precision across all queries = 0.3293846153846156
Mean Average Precision = 0.23286581196581202
Average nDCG = 0.28418444388847286
CPU times: user 10min 5s, sys: 6.9 s, total: 10min 12s
Wall time: 5min 37s

In [123]:
evaluate_kmeans_random_state_1100.head(10)

,ID,TEXT,Precision,Average Precision,nDCG
0,PLAIN-1,"[deep, fri, food, may, caus, cancer, latest, s...",0.800000,0.800000,0.710971
1,PLAIN-1007,"[ddt, persist, organ, pollut, industri, toxin,...",0.500000,0.166667,0.315648
2,PLAIN-101,"[treat, multipl, sclerosi, diet, multipl, scle...",0.400000,0.233333,0.298776
3,PLAIN-1017,"[detoxif, cancer, raw, food, heart, health, he...",0.000000,0.000000,0.000000
4,PLAIN-1027,"[dietari, guidelin, heart, diseas, cardiovascu...",0.000000,0.000000,0.000000
5,PLAIN-1038,"[dog, meat, anim, product, cat, heart, health,...",0.000000,0.000000,0.000000
6,PLAIN-1049,"[dr, heart, health, heart, diseas, egg, choles...",0.000000,0.000000,0.000000
7,PLAIN-1065,"[dr, walter, mortal, heart, diseas, heart, hea...",0.333333,0.066667,0.169580
8,PLAIN-1077,"[thyroid, health, hijiki, sushi, iodin, sea, v...",0.600000,0.600000,0.722727
9,PLAIN-1087,"[easter, island, mortal, muscl, strength, morb...",0.200000,0.050000,0.146068

In [124]:
evaluate_kmeans_random_state_1100.describe()

        Precision  Average Precision        nDCG
count  325.000000         325.000000  325.000000
mean     0.329385           0.232866    0.284184
std      0.350417           0.311427    0.315671
min      0.000000           0.000000    0.000000
25%      0.000000           0.000000    0.000000
50%      0.200000           0.066667    0.169580
75%      0.600000           0.383333    0.500000
max      1.000000           1.000000    1.000000